env:
  global:
    - LC_CTYPE=en_US.UTF-8
matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode9
      script:
        - swift build
        - swift run pst-lite
    - os: linux
      language: generic
      rvm:
        - 2.2
        - jruby
        - 2.0.0-p247
      sudo: required
      dist: trusty
      install:
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      script:
        - swift build
        - swift run pst-lite
